service: harbour-contractors-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: eu-west-2

functions:
  function1:
    handler: index.handler
    events:
      - httpApi:
          path: /test
          method: get
  listProjectImages:
    handler: listProjectImages.handler
    events:
      - httpApi:
          path: /listProjectImages/{projectName}
          method: get

iamRoleStatements:
  - Effect: Allow
    Action:
      - s3:ListBucket
      - s3:GetObject
    Resource:
      - arn:aws:s3:::harbourcontractorsimages
      - arn:aws:s3:::harbourcontractorsimages/*
