service: harbour-contractors-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: eu-west-2
  environment:
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
    TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER}
  httpApi:
    cors: true

functions:
  function1:
    handler: index.handler
    events:
      - httpApi:
          path: /test
          method: get
  sendMessage:
    handler: sendMessage.sendMessage
    events:
      - httpApi:
          path: /sendMessage
          method: post
  listProjectImages:
    handler: listProjectImages.handler
    events:
      - httpApi:
          path: /listProjectImages/{projectName}
          method: get
