org: iainhoolahan
app: harbour-contractors-lambda
service: harbour-contractors-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
